language: node_js
before_install: cd adaptive-arp-ts
node_js:
- '0.12'
install:
- npm install -g typescript
- npm install -g replace
before_script:
script:
- ./compile.sh
after_success:
- git ls-files --others --exclude-standard
after_failure:
- echo "Having a bad moment..."

